### ISSUE TITLE
请问可以提供课件原件吗？

### ISSUE THREAD

**Issue by atlasforever** [Kami-code/SE3357-2022-Notes#1]
您好，请问可以提供ppt/pdf的课件原件吗？网上公开的只能看到2021年的，许多内容不包含在里面。。。

感谢。

**Comment by Kami-code** [comment]
2022年课件：https://drive.google.com/file/d/1xPV0ibvzqCqfnIAlRJN6yd1Q5CzJc_AR/view?usp=sharing

版权声明
_

> 本内容版权归上海交通大学并行与分布式系统研究所所有
> 使用者可以将全部或部分本内容免费用于非商业用途
> 使用者在使用全部或部分本内容时请注明来源
> - 内容来自：上海交通大学并行与分布式系统研究所+材料名字
> 对于不遵守此声明或者其他违法使用本内容者，将依法保留追究权
> 本内容的发布采用 Creative Commons Attribution 4.0 License
> - 完整文本：https://creativecommons.org/licenses/by/4.0/legalcode

_
